server:
  port: 18002
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xiaominfo.springdoc
  default-flat-param-object: true
spring:
  application:
    name: knife4j-customer-sringdoc